/// Flutter icons MoviesAppIcons
library movies_app_icons;

/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MoviesAppIcons
///      fonts:
///       - asset: fonts/MoviesAppIcons.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MoviesAppIcons {
  static const IconData heart = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData emptyHeart = IconData(0xe801, fontFamily: _kFontFam);
  static const _kFontFam = 'MoviesAppIcons';

  MoviesAppIcons._();
}
