name: movies_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.5

dependencies:
  cloud_firestore: ^4.8.2
  dio: ^5.2.1+1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_remote_config: ^4.2.3
  flutter:
    sdk: flutter
  flutter_rating_stars: ^1.0.3+4
  flutter_signin_button: ^2.0.0
  get: ^4.6.5
  google_sign_in: ^6.1.4
  intl: ^0.18.1
  transparent_image: ^2.0.1

dev_dependencies:
  dart_code_metrics: ^5.7.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: MoviesAppIcons
      fonts:
        - asset: assets/fonts/MoviesAppIcons.ttf
    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
        - asset: assets/fonts/metropolis/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/metropolis/Metropolis-Bold.otf
