name: movies_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cloud_firestore: ^4.1.0
  dio: ^4.0.6
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  firebase_remote_config: ^3.0.6
  flutter:
    sdk: flutter
  flutter_rating_stars: ^1.0.3+4
  flutter_signin_button: ^2.0.0
  get: ^4.6.5
  google_sign_in: ^5.4.2
  intl: ^0.17.0
  transparent_image: ^2.0.0

dev_dependencies:
  dart_code_metrics: ^5.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: MoviesAppIcons
      fonts:
        - asset: assets/fonts/MoviesAppIcons.ttf
    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
        - asset: assets/fonts/metropolis/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/metropolis/Metropolis-Bold.otf
